# Site settings
title: Seven Times Have I...
email: jz2673@columbia.edu
description: > # this means to ignore newlines until "baseurl:"
  What's my name?
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

# Disqus post comments
disqus_shortname: seven-times-have-i

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  digest:
    output: true
    permalink: /digest/:path/

# Gems
gems: [jekyll-paginate]


